# WARPnet Client<->Server Architecture
# WARPnet Parameter Definitions
#
# Author: Siddharth Gupta


# Packet Type codes for Client<->Server communication

SC_STAT = 100

SC_DATA_TO_NODE = 110
SC_DATA_FROM_NODE = 111
SC_DATA_TO_NODE_REFLECT = 112

SC_GRPID_ADD = 120
SC_GRPID_DEL = 121

SC_CONNECT = 130

SC_REG_ADD = 200
SC_REG_DEL = 201

SC_LOCK = 210
SC_UNLOCK = 211
SC_LOCK_NOTIFICATION = 212
SC_UNLOCK_NOTIFICATION = 213

SC_EMULATOR_PRESENT = 300
SC_EMULATOR_MSG_TO_BOX = 301
SC_EMULATOR_MSG_FROM_BOX = 302

# Status Codes

SC_STAT_GROUP_UNMATCHED = 1
SC_STAT_NOT_CONN_NODE = 2
SC_NOT_REGISTERED = 3
SC_GRPID_GROUP_KNOWN = 4
SC_GRPID_SUCCESS = 5
SC_REG_SUCCESS = 6
SC_LOCK_EXISTS = 7
SC_LOCK_SUCCESS = 8
SC_LOCK_NOLOCK = 9
SC_LOCK_NOT_OWNER = 10
SC_CONNECT_SUCCESS = 12
SC_CONNECT_TYPE_MISMATCH = 13
SC_CONNECT_UNKNOWN_TYPE = 14
SC_DATA_LOCKED = 15
C_TIMEOUT = 16


# Registration Access Levels
ADDRESSED_TO_ME = 0
ADDRESSED_TO_MY_GROUP = 1
ADDRESSED_TO_ANY_GROUP = 2

MAKE_AVAIL_ME = 0
MAKE_AVAIL_MY_GROUP = 1
MAKE_AVAIL_ANY_GROUP = 2


# Node Connection Types
NODE_PCAP = 0
NODE_SOCKET = 1
NODE_LR = 2

