#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:C:\localhome\chunter\EDK\interrupt_reference_design\system.xmp
#################################################################

XILINX_EDK_DIR = C:/EDK

SYSTEM = system

MHSFILE = system.mhs

MSSFILE = system.mss

FPGA_ARCH = virtex2p

DEVICE = xc2vp70ff1517-6

LANGUAGE = vhdl

SEARCHPATHOPT =  -lp C:/localhome/chunter/user_repo/

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(SUBMODULE_OPT)

LIBGEN_OPTIONS = -mhs $(MHSFILE) -p $(DEVICE) $(SEARCHPATHOPT)

VPGEN_OPTIONS = -p $(DEVICE) $(SEARCHPATHOPT)

INTERRUPTTESTRBETA_OUTPUT_DIR = interruptTestrBeta
INTERRUPTTESTRBETA_OUTPUT = $(INTERRUPTTESTRBETA_OUTPUT_DIR)/executable.elf

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

PPC405_0_BOOTLOOP = $(BOOTLOOP_DIR)/ppc405_0.elf

PPC405_1_BOOTLOOP = $(BOOTLOOP_DIR)/ppc405_1.elf

BRAMINIT_ELF_FILES =  $(INTERRUPTTESTRBETA_OUTPUT) 
BRAMINIT_ELF_FILE_ARGS =   -pe ppc405_0 $(INTERRUPTTESTRBETA_OUTPUT) 

ALL_USER_ELF_FILES = $(INTERRUPTTESTRBETA_OUTPUT) 

SIM_CMD = vsim

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM).do

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM).do

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM).do

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

MIX_LANG_SIM_OPT = -mixed yes

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(LANGUAGE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_FILE_ARGS) $(MIX_LANG_SIM_OPT)  -s mti


LIBRARIES =  \
       ppc405_0/lib/libxil.a  \
       ppc405_1/lib/libxil.a 
VPEXEC = virtualplatform/vpexec.exe

LIBSCLEAN_TARGETS = ppc405_0_libsclean ppc405_1_libsclean 

PROGRAMCLEAN_TARGETS = interruptTestrBeta_programclean 

CORE_STATE_DEVELOPMENT_FILES = 

WRAPPER_NGC_FILES = implementation/ppc405_0_wrapper.ngc \
implementation/ppc405_1_wrapper.ngc \
implementation/jtagppc_0_wrapper.ngc \
implementation/reset_block_wrapper.ngc \
implementation/iocm_wrapper.ngc \
implementation/iocm_cntlr_wrapper.ngc \
implementation/isocm_bram_wrapper.ngc \
implementation/docm_wrapper.ngc \
implementation/docm_cntlr_wrapper.ngc \
implementation/dsocm_bram_wrapper.ngc \
implementation/plb_wrapper.ngc \
implementation/opb_wrapper.ngc \
implementation/plb2opb_wrapper.ngc \
implementation/leds_4bit_wrapper.ngc \
implementation/push_buttons_4bit_wrapper.ngc \
implementation/rs232_wrapper.ngc \
implementation/plb_bram_if_cntlr_1_wrapper.ngc \
implementation/plb_bram_if_cntlr_1_bram_wrapper.ngc \
implementation/opb_intc_0_wrapper.ngc \
implementation/dcm_0_wrapper.ngc \
implementation/opb_timer_0_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(BITGEN_UT_FILE) $(XFLOW_DEPENDENCY)

#################################################################
# SOFTWARE APPLICATION INTERRUPTTESTRBETA
#################################################################

INTERRUPTTESTRBETA_SOURCES = src/interruptTester.c 

INTERRUPTTESTRBETA_HEADERS = 

INTERRUPTTESTRBETA_CC = powerpc-eabi-gcc
INTERRUPTTESTRBETA_CC_SIZE = powerpc-eabi-size
INTERRUPTTESTRBETA_CC_OPT = -O2
INTERRUPTTESTRBETA_CFLAGS = 
INTERRUPTTESTRBETA_CC_SEARCH = # -B
INTERRUPTTESTRBETA_LIBPATH = -L./ppc405_0/lib/ # -L
INTERRUPTTESTRBETA_INCLUDES = -I./ppc405_0/include/ # -I
INTERRUPTTESTRBETA_LFLAGS = # -l
INTERRUPTTESTRBETA_LINKER_SCRIPT = interruptTestrBeta_linker_script.ld
INTERRUPTTESTRBETA_LINKER_SCRIPT_FLAG = -Wl,-T -Wl,$(INTERRUPTTESTRBETA_LINKER_SCRIPT) 
INTERRUPTTESTRBETA_CC_DEBUG_FLAG = # -[g|gstabs]
INTERRUPTTESTRBETA_CC_PROFILE_FLAG = # -pg
INTERRUPTTESTRBETA_CC_GLOBPTR_FLAG= # -msdata=eabi
INTERRUPTTESTRBETA_CC_START_ADDR_FLAG=  #  # -Wl,-defsym -Wl,_START_ADDR=
INTERRUPTTESTRBETA_CC_STACK_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_STACK_SIZE=
INTERRUPTTESTRBETA_CC_HEAP_SIZE_FLAG=  #  # -Wl,-defsym -Wl,_HEAP_SIZE=
INTERRUPTTESTRBETA_OTHER_CC_FLAGS= $(INTERRUPTTESTRBETA_CC_GLOBPTR_FLAG)  \
                  $(INTERRUPTTESTRBETA_CC_START_ADDR_FLAG) $(INTERRUPTTESTRBETA_CC_STACK_SIZE_FLAG) $(INTERRUPTTESTRBETA_CC_HEAP_SIZE_FLAG)  \
                  $(INTERRUPTTESTRBETA_LINKER_SCRIPT_FLAG) $(INTERRUPTTESTRBETA_CC_DEBUG_FLAG) $(INTERRUPTTESTRBETA_CC_PROFILE_FLAG) 
